# Generated by Django 2.2.4 on 2019-09-19 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0002_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='person',
        ),
    ]
