# Generated by Django 2.2.4 on 2019-09-19 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_remove_person_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='bidder',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='models.Person'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='buyer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer', to='models.Person'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to='models.Person'),
        ),
    ]
